### PR TITLE
Add a next button on success

### LINKED ISSUE #26: Add a "next" button to successfully completed problem page

### PR DESCRIPTION
**Pull request by doomspork**
Hi @pgr0ss, thanks for putting this project together.  This PR adds a "Next problem" link on successful completion, it closes #26.

### CODE REVIEW

**Comment by pgr0ss** [comment]
Thanks for submitting a pull request.

One issue I noticed: on the last problem, it builds a link to a non-existent next problem, which fails when you click on it. Other than this, your code looks good.

**Comment by doomspork** [comment]
Good catch @pgr0ss, sorry about that!  I made a change to the code to handle the last problem but it's not pretty, let me know your thoughts:

```elixir
<%= if @result == :passed && @problem.number < 17 do %>
```

**Comment by pgr0ss** [comment]
I wouldn't hardcode 17, since the number of problems can change. I think I would move the logic to `ProblemView` and then get the total number of problems from `ProblemList`.

**Comment by doomspork** [comment]
@pgr0ss sounds good, I'll take a peek at that.  Thanks.

**Comment by doomspork** [comment]
Thanks again for the feedback @pgr0ss, I went ahead and made those changes.  Let me know your thoughts.

**Comment by pgr0ss** [comment]
One more minor thing: can you rename `show_next_button` to `show_next_button?`? Then, I think it's ready to be pulled in. Thanks.

**Comment by doomspork** [comment]
@pgr0ss done, thanks again.

**Comment by doomspork** [comment]
Thanks @pgr0ss!  Have a great Sunday.

**Pull request merged**
